// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ContosoUniversity.Infrastructure;
using ContosoUniversity.Infrastructure.Data;
using ContosoUniversity.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace ContosoUniversity.Infrastructure.Data.Configurations
{
    public partial class CourseAssignmentConfiguration : IEntityTypeConfiguration<CourseAssignment>
    {
        public void Configure(EntityTypeBuilder<CourseAssignment> entity)
        {
            entity.HasKey(e => new { e.CourseId, e.InstructorId });

            entity.ToTable("CourseAssignment");

            entity.Property(e => e.CourseId).HasColumnName("CourseID");

            entity.Property(e => e.InstructorId).HasColumnName("InstructorID");

            entity.HasOne(d => d.Course)
                .WithMany(p => p.CourseAssignments)
                .HasForeignKey(d => d.CourseId);

            entity.HasOne(d => d.Instructor)
                .WithMany(p => p.CourseAssignments)
                .HasForeignKey(d => d.InstructorId);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CourseAssignment> entity);
    }
}
