<Project>

	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>

	<ItemGroup>
		<PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.301" />
		<PackageVersion Include="AutoMapper" Version="14.0.0" />
		<PackageVersion Include="DelegateDecompiler.EntityFrameworkCore5" Version="0.35.3" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageVersion Include="Microsoft.EntityFrameworkCore" Version="[8.0.27,9.0)" />
		<PackageVersion Include="EFCore.BulkExtensions" Version="[8.1.3,9.0)" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<PackageVersion Include="Microsoft.EntityFrameworkCore" Version="[9.0.16,10.0)" />
		<PackageVersion Include="EFCore.BulkExtensions" Version="[9.0.2,10.0)" />
			<PackageVersion Include="EFCore.BulkExtensions.Core" Version="[9.0.2,10.0)" />
		<PackageVersion Include="EFCore.BulkExtensions.SqlServer" Version="[9.0.2,10.0)" />
	</ItemGroup>	
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<PackageVersion Include="Microsoft.EntityFrameworkCore" Version="[10.0.8,11.0)" />
	</ItemGroup>

</Project>
