// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using makeITeasy.CarCatalog.dotnet9.Infrastructure.Data;
using makeITeasy.CarCatalog.dotnet9.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace makeITeasy.CarCatalog.dotnet9.Infrastructure.Data.Configurations
{
    public partial class CompositeKeySubTableConfiguration : IEntityTypeConfiguration<CompositeKeySubTable>
    {
        public void Configure(EntityTypeBuilder<CompositeKeySubTable> entity)
        {
            entity.ToTable("CompositeKeySubTable");

                entity.Property(e => e.Value)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.HasOne(d => d.CompositeKeyTable)
                    .WithMany(p => p.CompositeKeySubTables)
                    .HasForeignKey(d => new { d.ParentKey1, d.ParentKey2 })
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_CompositeKeySubTable_ToCompositeKeyTable");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CompositeKeySubTable> entity);
    }
}
