// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using makeITeasy.CarCatalog.dotnet9.Infrastructure.Data;
using makeITeasy.CarCatalog.dotnet9.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace makeITeasy.CarCatalog.dotnet9.Infrastructure.Data.Configurations
{
    public partial class CompositeKeyTableConfiguration : IEntityTypeConfiguration<CompositeKeyTable>
    {
        public void Configure(EntityTypeBuilder<CompositeKeyTable> entity)
        {
            entity.HasKey(e => new { e.Id1, e.Id2 });

                entity.ToTable("CompositeKeyTable");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CompositeKeyTable> entity);
    }
}
