<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Serilog" Version="4.3.1" />
	</ItemGroup>


	<ItemGroup>
		<ProjectReference Include="..\..\src\makeITeasy.AppFramework.Infrastructure.EntityFramework\makeITeasy.AppFramework.Infrastructure.EntityFramework.csproj" />
		<ProjectReference Include="..\makeITeasy.CarCatalog.dotnet8.Core\makeITeasy.CarCatalog.dotnet8.Core.csproj" />
		<ProjectReference Include="..\makeITeasy.CarCatalog.dotnet8.Models\makeITeasy.CarCatalog.dotnet8.Models.csproj" />
	</ItemGroup>


	<ItemGroup>
	  <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.300" />
	</ItemGroup>
	<ItemGroup>
		<NuGetAuditSuppress Include="https://github.com/advisories/GHSA-rvv3-g6hj-g44x" PackageId="AutoMapper" Reason="Known advisory; internal work around applied" />
		<PackageVersion Include="AutoMapper" Version="14.0.0" />
	</ItemGroup>
</Project>
